[project]
name = "aibox-nes-slms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel==6.30.1",
    "ipywidgets==8.1.7",
    "kagglehub>=0.3.13",
    "matplotlib>=3.10.7",
    "mlx-lm>=0.28.3",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
]
